const path = 'https://pokeapi.co/api/v2/'
const api = {
  ability: `${path}ability/`,
  berry: `${path}berry/`,
  berryfirmness: `${path}berry-firmness/`,
  berryflavor: `${path}berry-flavor/`,
  characteristic: `${path}characteristic/`,
  contesteffect: `${path}contest-effect/`,
  contesttype: `${path}contest-type/`,
  egggroup: `${path}egg-group/`,
  encountercondition: `${path}encounter-condition/`,
  encounterconditionvalue: `${path}encounter-condition-value/`,
  encountermethod: `${path}encounter-method/`,
  evolutionchain: `${path}evolution-chain/`,
  evolutiontrigger: `${path}evolution-trigger/`,
  gender: `${path}gender/`,
  generation: `${path}generation/`,
  growthrate: `${path}growth-rate/`,
  item: `${path}item/`,
  itemattribute: `${path}item-attribute/`,
  itemcategory: `${path}item-category/`,
  itemflingeffect: `${path}item-fling-effect/`,
  itempocket: `${path}item-pocket/`,
  language: `${path}language/`,
  location: `${path}location/`,
  locationarea: `${path}location-area/`,
  machine: `${path}machine/`,
  move: `${path}move/`,
  moveailment: `${path}move-ailment/`,
  movebattlestyle: `${path}move-battle-style/`,
  movecategory: `${path}move-category/`,
  movedamageclass: `${path}move-damage-class/`,
  movelearnmethod: `${path}move-learn-method/`,
  movetarget: `${path}move-target/`,
  nature: `${path}nature/`,
  palparkarea: `${path}pal-park-area/`,
  pokeathlonstat: `${path}pokeathlon-stat/`,
  pokedex: `${path}pokedex/`,
  pokemon: `${path}pokemon/`,
  pokemoncolor: `${path}pokemon-color/`,
  pokemonform: `${path}pokemon-form/`,
  pokemonhabitat: `${path}pokemon-habitat/`,
  pokemonshape: `${path}pokemon-shape/`,
  pokemonspecies: `${path}pokemon-species/`,
  region: `${path}region/`,
  stat: `${path}stat/`,
  supercontesteffect: `${path}super-contest-effect/`,
  type: `${path}type/`,
  version: `${path}version/`,
  versiongroup: `${path}version-group/`
}

export default api
